coffee_chain_athena:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: athena
      region_name: "{{ env_var('AWS_DEFAULT_REGION', 'us-east-1') }}"
      s3_staging_dir: "{{ env_var('ATHENA_RESULTS') }}"
      schema: coffee_chain_dev
      database: awsdatacatalog
      s3_data_dir: "s3://{{ env_var('S3_BUCKET') }}/gold/"
      s3_data_naming: schema_table
      work_group: "{{ env_var('ATHENA_WORKGROUP', 'primary') }}"
      threads: 4

    prod:
      type: athena
      region_name: "{{ env_var('AWS_DEFAULT_REGION', 'us-east-1') }}"
      s3_staging_dir: "{{ env_var('ATHENA_RESULTS') }}"
      schema: coffee_chain_prod
      database: awsdatacatalog
      s3_data_dir: "s3://{{ env_var('S3_BUCKET') }}/gold/"
      s3_data_naming: schema_table
      work_group: "{{ env_var('ATHENA_WORKGROUP', 'primary') }}"
      threads: 4
